---
# tasks file for haproxy

- name: Install HAProxy, Redhat
  yum:
    name: haproxy
    state: present
    update_cache: yes

- name: Setup HAProxy Config
  template:
    src: "{{ haproxy_template_cofig }}"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy
